package service

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/arsenh/DevLore/internal/database"
	"github.com/arsenh/DevLore/internal/logger"
	"github.com/arsenh/DevLore/internal/model"
	"github.com/arsenh/DevLore/internal/repository"
	"github.com/google/uuid"
)

type UserService struct {
	userRepository model.UserRepository
}

func NewUserService(db *database.DbContext) *UserService {
	return &UserService{
		userRepository: repository.NewPostgresUserRepository(db),
	}
}

func (u *UserService) GetUserByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	user, err := u.userRepository.FindByID(ctx, id)

	if errors.Is(err, repository.ErrUserNotFound) {
		return nil, fmt.Errorf("user with id: %s not found in database", id.String())
	}

	if err != nil {
		return nil, fmt.Errorf("failed to get info about user id = %s", id.String())
	}

	return user, nil
}

func (u *UserService) RegisterUser(ctx context.Context, email string, password string, fullName string) (*model.User, error) {

	// ID for user will be generated by Database
	user := &model.User{
		FullName:  fullName,
		Email:     email,
		Password:  password, // TODO: need to create HASH on password
		CreatedAt: time.Now(),
	}

	err := u.userRepository.Create(ctx, user)
	if err != nil {
		return nil, fmt.Errorf("failed to register user by email: %s", email)
	}

	return user, nil
}

func (u *UserService) GetUserByEmail(ctx context.Context, email string) *model.User {
	user, err := u.userRepository.FindByEmail(ctx, email)

	if errors.Is(err, repository.ErrUserNotFound) {
		logger.L().Warningf("user with email: %s not found in database", email)
		return nil
	}

	if err != nil {
		logger.L().Warningf("failed to get info about user email = %s", email)
		return nil
	}

	return user
}

func (u *UserService) CheckUserPassword(ctx context.Context, userID uuid.UUID, inputPassword string) bool {
	user, err := u.userRepository.FindByID(ctx, userID)
	if err != nil {
		return false
	}

	//TODO: In real database, need to compare hashes, from user input and database hash
	return user.Password == inputPassword
}
